# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7', '3.0']
        activerecord: ['6.0', '6.1', '7.0']
        experimental: [false]
        exclude:
        - ruby: '2.5'
          activerecord: '7.0'
          experimental: false
        - ruby: '2.6'
          activerecord: '7.0'
          experimental: false
        - ruby: '3.0'
          activerecord: '6.0'
          experimental: false
        include:
        # waiting for a release of https://github.com/rails/rails/pull/39697
        - ruby: '3.0'
          activerecord: '6.0'
          experimental: true
    continue-on-error: ${{ matrix.experimental }}
    env:
      APPRAISAL: rails_${{ matrix.activerecord }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        bundle install
        bundle exec appraisal $APPRAISAL bundle install
    - name: Run tests
      run: bundle exec appraisal $APPRAISAL rake
